apiVersion: v1
kind: Service
metadata:
  name: service-jenkins
  namespace: jenkins
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
    metallb.universe.tf/ip-allocated-from-pool: pool
spec:
  selector:
    app: server-jenkins
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
